### ISSUE TITLE
Unreasonable CitySim Coupled for QN

### ISSUE THREAD

**Issue by cmiller8** [architecture-building-systems/umem-jbps-paper#1]
Ok, so I fixed the QN E+ graphics and they look very reasonable now.

I ran into an issue with the QN CitySim results though: https://www.dropbox.com/s/45roo7vt7qxy1j4/Screenshot%202016-04-15%2012.59.21.png?dl=0

Solo CitySim makes sense but the Q(s) output for 1(1):1:Qs(Wh) results in crazy high cooling and NO heating:  https://www.dropbox.com/s/qht2l0sem3yloxz/Screenshot%202016-04-15%2013.03.42.png?dl=0

**Comment by cmiller8** [comment]
Looked at all 'zones' within the CitySim .TH for CoSimulation.

The third one makes sense for heating. None make sense for cooling -- either way to low or, in the case of #1, too high be a factor of 3.

<img width="955" alt="screenshot 2016-04-15 14 55 00" src="https://cloud.githubusercontent.com/assets/193675/14553635/2b685ff8-031a-11e6-8808-7221fa0ad2dd.png">

**Comment by jkaempf** [comment]
Hello Clayton,

First thing I checked for the co-sim / solo thing (your first question), and I can say that:
- for the co-sim (and I don't know why), you need to have a look at the columns heating and cooling, as when I co-sim I overwrite the result from E+ in these columns.. leaving Qs with an old value.
- the columns in the _TH file coming from E+ are: Ta, Heating, Cooling, VdotVent
- the columns in the _TS file coming from E+ are: Wall temperatures and Roof temperatures

Second thing, and this maybe more for Daren: I checked the output of E+ in the co-sim, and we have an inside air temperature of 40°C when it should be 20°C and 44°C when it should be 40°C. The factor 2 seems to be the number of zones. Daren can you check the variable exchanged named: Mean Air Temperature ?

Last thing: the other zones in the file (3,4 and 5) are the other buildings around and should not be considered..

**Comment by cmiller8** [comment]
Great -- that fixed my issues as the results make sense again.

I guess Daren can help troubleshoot the indoor temp

**Comment by daren-thomas** [comment]
sure. I will take a look at the room temp!

**Comment by daren-thomas** [comment]
OK. Yes. I made a stupid mistake. @jaykae26, you are right: The room temperatures are added up. I will correct this!

**Comment by daren-thomas** [comment]
@jaykae26: I am having trouble running the co-simulation for quartier-nord: it seems you have moved stuff around in the dropbox a bit. could you take a look?

**Comment by jkaempf** [comment]
I just changed the paths in the vistrail.. quartier-nord.vt

**Comment by cmiller8** [comment]
I think this is done, right?
